# Change these first
owner: gabi200 # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: Minecraft server
    url: 141.147.28.179
    check: "tcp-ping"
    port: 25565
  - name: Jellyfin Public Endpoint
    url: https://services.gabi.eu.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /uptime-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: Gabi's System Status Page
  introMessage: Below is the status of all the public services.

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
